/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental_cosplay;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author couser
 */
public class register extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    
    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        k.connect();
        refreshTable();
    }
    
    class user extends register{
        int id_user;
        String username, password, nama_user, telepon, alamat, level;
        
        public user() {
            username = text_username.getText();
            password = text_password.getText();
            nama_user = text_nama_user.getText();
            telepon = text_telepon.getText();
            alamat = text_alamat.getText();
            level = combo_level.getSelectedItem().toString();
        }
    }
    
    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("ID User");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Nama User");
        model.addColumn("Telepon");
        model.addColumn("Alamat");
        model.addColumn("Sebagai");
        table_register.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("select * from user");
            this.rs = this.stat.executeQuery();
            while (rs.next()){
                Object[] data = {
                    rs.getString("id_user"),
                    rs.getString("username"),
                    rs.getString("password"),
                    rs.getString("nama_user"),
                    rs.getString("telepon"),
                    rs.getString("alamat"),
                    rs.getString("level")
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        text_id_user.setText("");
        text_username.setText("");
        text_password.setText("");
        text_nama_user.setText("");
        text_telepon.setText("");
        text_alamat.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        text_id_user = new javax.swing.JTextField();
        text_username = new javax.swing.JTextField();
        text_password = new javax.swing.JTextField();
        text_nama_user = new javax.swing.JTextField();
        text_telepon = new javax.swing.JTextField();
        text_alamat = new javax.swing.JTextField();
        combo_level = new javax.swing.JComboBox<>();
        btn_kembali = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_register = new javax.swing.JTable();
        btn_register = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_id_user.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        text_id_user.setEnabled(false);
        text_id_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_id_userActionPerformed(evt);
            }
        });
        getContentPane().add(text_id_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 570, 60));

        text_username.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 570, 50));

        text_password.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 570, 60));

        text_nama_user.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(text_nama_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 570, 50));

        text_telepon.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        getContentPane().add(text_telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 570, 50));

        text_alamat.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        text_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_alamatActionPerformed(evt);
            }
        });
        getContentPane().add(text_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 570, 60));

        combo_level.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        combo_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user" }));
        getContentPane().add(combo_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 160, 50));

        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 120, 50));

        table_register.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        table_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_registerMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_register);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 700, 299));

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 120, 70));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 120, 70));

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 120, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menu register [0B09468].png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_id_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_id_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_id_userActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
    try {
        user u = new user();
        this.stat = k.getCon().prepareStatement(
            "INSERT INTO user (username, password, nama_user, telepon, alamat, level) VALUES (?, ?, ?, ?, ?, ?)"
        );
        stat.setString(1, u.username);
        stat.setString(2, u.password);
        stat.setString(3, u.nama_user);
        stat.setString(4, u.telepon);
        stat.setString(5, u.alamat);
        stat.setString(6, u.level);
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        refreshTable();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
        // TODO add your handling code here:
        Menu_admin reg = new Menu_admin();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_kembaliActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
                try {
            user u = new user();
            this.stat = k.getCon().prepareStatement("update user set username=?,"
                    + "password=?,nama_user=?,telepon=?,alamat=?,level=? where id_user=?");
            stat .setString(1, u.username);
            stat .setString(2, u.password);
            stat .setString(3, u.nama_user);
            stat .setString(4, u.telepon);
            stat.setString(5, u.alamat);
            stat.setString(6, u.level);
            stat.setString(7, text_id_user.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil dirubah!");
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan" + e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try {
            user u = new user();
            this.stat = k.getCon().prepareStatement("delete from user where id_user=?");
            stat.setString(1, text_id_user.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil Dihapus!");
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + e.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void text_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_alamatActionPerformed

    private void table_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_registerMouseClicked
        // TODO add your handling code here:
        text_id_user.setText(model.getValueAt(table_register.getSelectedRow(), 0).toString());
        text_username.setText(model.getValueAt(table_register.getSelectedRow(), 1).toString());
        text_password.setText(model.getValueAt(table_register.getSelectedRow(), 2).toString());
        text_nama_user.setText(model.getValueAt(table_register.getSelectedRow(), 3).toString());
        text_telepon.setText(model.getValueAt(table_register.getSelectedRow(), 4).toString());
        text_alamat.setText(model.getValueAt(table_register.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_table_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_kembali;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_level;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table_register;
    private javax.swing.JTextField text_alamat;
    private javax.swing.JTextField text_id_user;
    private javax.swing.JTextField text_nama_user;
    private javax.swing.JTextField text_password;
    private javax.swing.JTextField text_telepon;
    private javax.swing.JTextField text_username;
    // End of variables declaration//GEN-END:variables
}
